name: geocoder
description: Forward and reverse geocoding.
version: 0.0.1
author: Aloïs Deniel<alois.deniel@gmail.com>
homepage: https://github.com/aloisdeniel/flutter_geocoder

environment:
  sdk: '>=2.0.0-dev.33.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.aloisdeniel.geocoder
    pluginClass: GeocoderPlugin
